### ISSUE TITLE
How to delete a page/modify page name from Pages page?

### ISSUE THREAD

**Issue by raspher** [jamescarlyle/ipfs-wiki#2]
When something is useless or was a mistake, and i want to delete page, there isn't any way to do that by button... I think it should be something to avoid junk in wiki-page.

Or except deleting, maybe modify the name of a page? there is too no way to do that.

**Comment by jamescarlyle** [comment]
Thanks @raspher I'm taking a look at this concept again after 5.5 years :) Will consider this soft-delete idea.
